December 2021 RC v2.0 (#54)
* Initial version with additional logging and exception handling (using stubs)

* Added code for Learner Service

* Added stub db tables for saving results, and wired up save method in EmploymentChecksRepositoryStub to save to that db

* Removed sproc (no need for it, simple sql) and added sql straight into stub method

* Added Log() helper method to format custom logging messages

* Added new db save method to include ULN and use ULN in logging

* Implemented log helper for save method. Also added mechanism to remove existing rows that match new data to avoid errors when re-running the stubbed journey

* Changed delete sql command to update sql command and added more comprehensive logging to save method

* Addedd GetLearnersRequiringEmploymentCheck Activity function

* Added GetLearnersRequiringEmploymentChecks() to the EmploymentChecksRepository

* Added activity function and related mediator, serice and stub code for the Find PAYE schems element of the HLSD.

* Das employmentcheck add source data table (#31)

* Added account id  to dto

* Wired up db data retrieval

* Added operator to transform db return type to handler return type

* fixed cast

* Removed duplicate method from implementation and old stub method from stub service (replaced by GetLearnersRequiringEmploymentChecks)

* renamed variable to fix code smell

* Tidied up folder layout and refactored the GetEmployerPayeSchemes code.

* Das employmentcheck wire save function up to source data db table (#32)

* Commented out old method (method left in place due to implementing same interface as Mike's implementation. Re-wired save method to store check results in correct table

* Deleted stub table (no longer required)

* Deleted commented out old method to satisfy code smell

* Code cleanup and refactoring.

* Rremoved commented out original code for the test orchestrator

* Remove duplicate activity

* Added test project, added first activity tests

* added ni number activity tests

* added get apprentices activity tests

* Fixed extension that was failing the build

* Added missing release version of the services to the startup

* Added tests for check apprentice activity. Ignored by test runner and commented out since method is not yet implemented

* Added http trigger tests (log test helper not yet implemented)

* Added timer trigger test

* Created LoggerAdapter

* Implemented logger adapter in triggers and tested them

* Added ILoggerAdapter and implementation, implemented in place of all instances of ILogger

* Fixed ServiceCollectionExtensions missed from refactor

* Modified activity tests to use logger adapter

* Added command tests

* Added command handler tests

* Added get apprentices tests

* added get apprentice ni numbers tests

* minor refactoring

* added get apprentices to vefiry tests

* added get paye schemes tests

* Added tests for models

* logger refactoring

* WIP EmployerAccountApiClient tests

* removed WIP test, added tests for EmployerAccountClient

* Added EmploymentCheckClient tests

* added SubmitLearnerDataClient tests

* Removed usage of (broken) stub-only service

* Added EmployerAccountService tests

* Added HmrcService tests

* Removed ILoggerAdapter and ILoggerAdapter<T>, replaced all instances with ILogger and ILogger<T>. Unit tests are WIP, build will fail

* Fixed tests broken by removing ILoggerAdapter. 8 tests marked as skipped awaiting code implementation

* Refactoring to get the outline logic of the solution in place.

* Removed unused commented out code.

* Added some comments to the Orchestrator functions

* Various code fixes found after more extended testing. Still issues with storing the 'place holder' for the next batch and the initial condition of all tables being empty.

* HTB-44 MVS - Implement first HMRC API call (emp. check) HTB-17 Set up HMRC API test harness HTB-80 Add test data seeding tool (#48)

HTB-44 MVS - Implement first HMRC API call (emp. check)
HTB-17 Set up HMRC API test harness
HTB-80 Add test data seeding tool

* Merged updates from Gary's code

* Various code fixes

* Make [IsEmployed] NULLable as in the original table

* Htb 9 implement accounts api call (#51)

* Merged updates from Gary's code

* Various code fixes

* Make [IsEmployed] NULLable as in the original table

Co-authored-by: Peter Williams <peter.david.williams.1991@gmail.com>
Co-authored-by: ruslan <ruslanss@gmail.com>

* Add Polly Retry

* Re-use HMRC Auth token and save results

* Edit configuration code to prepare for release to test

* Startup - uncomment AddAzureTableStorage config section

EmploymentCheckServiceBase - log errors as errors instead of information
DataSeeder - enable Azure Db access

* Fix Error CS8652: The feature 'target-typed object creation' is currently in Preview and *unsupported*.

* Improve error reporting, change the order of the configs being applied

* enable rate-limiter, config refactoring

* HMRC API queue data seeder: add more options

* rate limiter delay using function context

* Remove dependency on Microsoft.Azure.Cosmos.Table, various rate-limiter improvements

* improve error logging

* Don't scream error when it isn't

* Make ReturnMessage VARCHAR(MAX) to resolve sql truncation errors

* HTB-4 implement DC API call (#50)

* added yaml for new sql deployment step template

* corrected indentation on sql task

* correcred file path for dacpac

* HTB-17 Set up HMRC API test harness

https://skillsfundingagency.atlassian.net/browse/HTB-17

* Add hmrc token auth service stub

* Move dependency registration

* Use TokenServiceStub in DEBUG mode

* Call HMRC API and save results

* Add ProcessApprenticeEmploymentChecksHttpTrigger

* rectify data types

* Added DC services to call learner API

* Store response code and message against the EmploymentChecks

* Add app-levy-data-seeder tool

* Drop NationalInsuranceNumber column from EmploymentChecks table

Store error responses

* Sort out EmploymentCheckService dependency registration

* Data-seeder - pick up all json files

* Fix SubmitLearnerDataService connection issues

* Seed better ULN data which returns NINOs

* Add CleanupOldWorkflows orchestrator

* remove duplicated code

* Add ApprenticeEmploymentCheckSeedDatabaseTestDataHttpTrigger, tidy-up DC API call code

* do not report error when there's nothing to do 🥱

Co-authored-by: EVANS <Christian.EVANS@EDUCATION.GOV.UK>
Co-authored-by: Peter Williams <peter.david.williams.1991@gmail.com>

* comment out EmploymentCheckTimer

* Defect - only log ReturnCode truncation sql errors due to a bug

* Enable all services

* enable accounts API to test on the env

* data-seeder: add option to seed [dbo].[EmploymentChecks] table only

* Add NINO back onto the EmploymentChecks, read accounts from a file for data-seeding

* don't reduce nino field size for now

* Use single config for accounts api client

* Combined DC config into one class and removed second class

* Removed extraneous secret, renamed scope

* Accounts API - add hashing service and correct config

* DataSeeder - use learners files if provided

* Enable Accounts API, add defensive code

* Various fixes for end-to-end process

* end-to-end working process

* re-use HmrcApiRateLimiterOptions to improve performance

* Handle NULL NINO / PAYE

* set EmploymentCheckedDateTime regardless of the result

* Do not insert duplicates into the queue ‼

* Update to DC API client to call 2122 endpoint

* HTB-93 [BUG] 🪲 When AccountId returns multiple PAYE schemes, multiple messages are created in the queue with only 1 paye scheme

* data seeder v0.2 - read from CSV data input file

* gitignore changes to data-seeder data file

* Allow multiple datasets

* HTB-97 - Upper Case PAYE to avoid HMRC returning 400 Bad Request

* Recover unit tests

* Address code review comments

* fix SonarQube issues

* tweak Logging setup code in attempt to satisfy SonarQube checks

Co-authored-by: Gary Griffiths <gary.griffiths@digital.education.gov.uk>
Co-authored-by: Craig Faulkner <86111246+notquitecraig@users.noreply.github.com>
Co-authored-by: ruslanss <ruslan.schelkunov@digital.education.gov.uk>
Co-authored-by: ruslan <ruslanss@gmail.com>
Co-authored-by: Gary-Griffiths-Digital-Education <91130066+Gary-Griffiths-Digital-Education@users.noreply.github.com>
Co-authored-by: EVANS <Christian.EVANS@EDUCATION.GOV.UK>