HTB-192 enable unit tests in ci pipeline (#94)
* Initial version with additional logging and exception handling (using stubs)

* Added code for Learner Service

* Added stub db tables for saving results, and wired up save method in EmploymentChecksRepositoryStub to save to that db

* Removed sproc (no need for it, simple sql) and added sql straight into stub method

* Added Log() helper method to format custom logging messages

* Added new db save method to include ULN and use ULN in logging

* Implemented log helper for save method. Also added mechanism to remove existing rows that match new data to avoid errors when re-running the stubbed journey

* Changed delete sql command to update sql command and added more comprehensive logging to save method

* Addedd GetLearnersRequiringEmploymentCheck Activity function

* Added GetLearnersRequiringEmploymentChecks() to the EmploymentChecksRepository

* Added activity function and related mediator, serice and stub code for the Find PAYE schems element of the HLSD.

* Das employmentcheck add source data table (#31)

* Added account id  to dto

* Wired up db data retrieval

* Added operator to transform db return type to handler return type

* fixed cast

* Removed duplicate method from implementation and old stub method from stub service (replaced by GetLearnersRequiringEmploymentChecks)

* renamed variable to fix code smell

* Tidied up folder layout and refactored the GetEmployerPayeSchemes code.

* Das employmentcheck wire save function up to source data db table (#32)

* Commented out old method (method left in place due to implementing same interface as Mike's implementation. Re-wired save method to store check results in correct table

* Deleted stub table (no longer required)

* Deleted commented out old method to satisfy code smell

* Code cleanup and refactoring.

* Rremoved commented out original code for the test orchestrator

* Remove duplicate activity

* Added test project, added first activity tests

* added ni number activity tests

* added get apprentices activity tests

* Fixed extension that was failing the build

* Added missing release version of the services to the startup

* Added tests for check apprentice activity. Ignored by test runner and commented out since method is not yet implemented

* Added http trigger tests (log test helper not yet implemented)

* Added timer trigger test

* Created LoggerAdapter

* Implemented logger adapter in triggers and tested them

* Added ILoggerAdapter and implementation, implemented in place of all instances of ILogger

* Fixed ServiceCollectionExtensions missed from refactor

* Modified activity tests to use logger adapter

* Added command tests

* Added command handler tests

* Added get apprentices tests

* added get apprentice ni numbers tests

* minor refactoring

* added get apprentices to vefiry tests

* added get paye schemes tests

* Added tests for models

* logger refactoring

* WIP EmployerAccountApiClient tests

* removed WIP test, added tests for EmployerAccountClient

* Added EmploymentCheckClient tests

* added SubmitLearnerDataClient tests

* Removed usage of (broken) stub-only service

* Added EmployerAccountService tests

* Added HmrcService tests

* Removed ILoggerAdapter and ILoggerAdapter<T>, replaced all instances with ILogger and ILogger<T>. Unit tests are WIP, build will fail

* Fixed tests broken by removing ILoggerAdapter. 8 tests marked as skipped awaiting code implementation

* Refactoring to get the outline logic of the solution in place.

* Removed unused commented out code.

* Added some comments to the Orchestrator functions

* Various code fixes found after more extended testing. Still issues with storing the 'place holder' for the next batch and the initial condition of all tables being empty.

* HTB-44 MVS - Implement first HMRC API call (emp. check) HTB-17 Set up HMRC API test harness HTB-80 Add test data seeding tool (#48)

HTB-44 MVS - Implement first HMRC API call (emp. check)
HTB-17 Set up HMRC API test harness
HTB-80 Add test data seeding tool

* Merged updates from Gary's code

* Various code fixes

* Make [IsEmployed] NULLable as in the original table

* Htb 9 implement accounts api call (#51)

* Merged updates from Gary's code

* Various code fixes

* Make [IsEmployed] NULLable as in the original table

Co-authored-by: Peter Williams <peter.david.williams.1991@gmail.com>
Co-authored-by: ruslan <ruslanss@gmail.com>

* Add CleanupOldWorkflows orchestrator

* Add Polly Retry

* Re-use HMRC Auth token and save results

* Edit configuration code to prepare for release to test

* fix release mode build

* Refactored to the database design.

* Add more data models

* WIP

* Startup - uncomment AddAzureTableStorage config section

EmploymentCheckServiceBase - log errors as errors instead of information
DataSeeder - enable Azure Db access

* Fix Error CS8652: The feature 'target-typed object creation' is currently in Preview and *unsupported*.

* More WIP

* Improve error reporting, change the order of the configs being applied

* enable rate-limiter, config refactoring

* HMRC API queue data seeder: add more options

* rate limiter delay using function context

* Remove dependency on Microsoft.Azure.Cosmos.Table, various rate-limiter improvements

* improve error logging

* Don't scream error when it isn't

* Make ReturnMessage VARCHAR(MAX) to resolve sql truncation errors

* Fixed merge conflicts

* Merge from HTB-53 Create new database

* HTB-4 implement DC API call (#50)

* added yaml for new sql deployment step template

* corrected indentation on sql task

* correcred file path for dacpac

* HTB-17 Set up HMRC API test harness

https://skillsfundingagency.atlassian.net/browse/HTB-17

* WIP

* Add hmrc token auth service stub

* Move dependency registration

* Use TokenServiceStub in DEBUG mode

* Call HMRC API and save results

* Add ProcessApprenticeEmploymentChecksHttpTrigger

* rectify data types

* Added DC services to call learner API

* Store response code and message against the EmploymentChecks

* Add app-levy-data-seeder tool

* Drop NationalInsuranceNumber column from EmploymentChecks table

Store error responses

* WIP

* Sort out EmploymentCheckService dependency registration

* Data-seeder - pick up all json files

* Fix SubmitLearnerDataService connection issues

* Seed better ULN data which returns NINOs

* Add CleanupOldWorkflows orchestrator

* remove duplicated code

* Add ApprenticeEmploymentCheckSeedDatabaseTestDataHttpTrigger, tidy-up DC API call code

* do not report error when there's nothing to do 🥱

Co-authored-by: EVANS <Christian.EVANS@EDUCATION.GOV.UK>
Co-authored-by: Peter Williams <peter.david.williams.1991@gmail.com>

* comment out EmploymentCheckTimer

* Defect - only log ReturnCode truncation sql errors due to a bug

* Enable all services

* enable accounts API to test on the env

* WIP fixed api call url

* data-seeder: add option to seed [dbo].[EmploymentChecks] table only

* WIP 1

* Fixed merge conflicts

* Add NINO back onto the EmploymentChecks, read accounts from a file for data-seeding

* don't reduce nino field size for now

* Use single config for accounts api client

* Refactoring to use new database tables and names.

* Fixed NationalInsuranceNumber typo

* Combined DC config into one class and removed second class

* Removed extraneous secret, renamed scope

* Accounts API - add hashing service and correct config

* DataSeeder - use learners files if provided

* Enable Accounts API, add defensive code

* Various fixes for end-to-end process

* end-to-end working process

* re-use HmrcApiRateLimiterOptions to improve performance

* Fixes for:
  Getting the highest batch id
  Handling for NI number not being found
  Handling for PAYE scheme not being found
  Refactoring of seed code as a result of the new DB models

* Post merge from dec RC fixups

* Fixed JSON error on startup relating to the change of the Correlation Id to a GUID
Added validation in CreateEmploymentMessage to check valid values have been supplied before creating a message.

* Fixed the storing of the message on the queue issue as a result of renaming reponseId to responseHttpStatusCode.

* Removed duplicate classes leftover from the merge from Dec 21 RC.
Added validation for the result returned from the GetEmploymentStatus() call.

* Fix SQL insert and delete statement in SaveEmploymentCheckResult.
ProcessEmploymentCheckOrchestrator now dequeues a message, send it to the HMRC Api, saves the result (with error if appropriate )in the EmploymentCheck table and archives the message in the message history table.

* EmploymentCheckCacheRequest WIP

* API request/response WIP

* Initial version of Jan 2022 v2 RC

* Fixed the GetBatch() sql where the batch parameter was incorrect.

* merge master, fix unit tests (#75)

* merge master, fix unit tests 🔀
* delete redundant codez 🚮
* update data-seeding tool 🆙

* Switch to NUnit.Framework

* delete more codez 🚮

* Merge branch 'master' of https://github.com/SkillsFundingAgency/das-employmentcheck into Jan-2022-v2-RC

* Move DcApiSettings, add Dapper table attributes

* Fix fetching of db connection string, inject azureServiceTokenProvider

* Do not use database name pre-fix in SQL commands

* Fix DC URL

* HTB-84 reduce logging, delete commented out and stub and zombie code

* Add defensive code

* do not throw exceptions for successful DC Api responses (e.g. 204)

* rollback host.json changes for reduced function logging

* fixes

EmploymentCheck
1. Change EmploymentCheck table column CorrelationId definition to NOT NULL

2. Add EmploymentCheck table column RequestCompletionStatus column NULLABLE
(Holds processing error statuses to stop an employment check being re-read after it has been processed and failed (e.g. Nino not found or PayeScheme not found)

3. Include the RequestCompletionStatus column in the 'GetEmploymentCheckBatch' db query
(To prevent failed error checks being re-read (possible exception for specific system time errors for time-outs, too many requests etc).

* Included Response body from exception in the database save.

* Htb 182 jan v2 code when hmrc api response is not 200 duplicate records are created in cache.employment check cache response table (#81)

* Replaced the criteria for reading the EmploymentCheckCacheResponse table with RequestCompletionStatus = null or 0 instead of using Employer IS NULL

* Fixed last PR, didn't remove the test code.

* Htb 182 jan v2 code when hmrc api response is not 200 duplicate records are created in cache.employment check cache response table (#83)

* Replaced the criteria for reading the EmploymentCheckCacheResponse table with RequestCompletionStatus = null or 0 instead of using Employer IS NULL

* Fixed last PR, didn't remove the test code.

* Set the EmploymentCheckTable RequestCompletionStatus to 'Started' after reading from DB.

* Added 'IF NOT EXISTS' check before inserting rows into key tables to avoid the exceptions thrown from the table constraints and fixed the updating of the RequestCompletionStatus flag.

* Removed commented out code.

* Removed redundant checking in GetEmploymentCheckBatch and GetEmploymentCheckCacheRequest

* HTB-181 Store error responses returned by HMRC API , use Dapper for saving data, add unit tests (#84)

* HTB-181 Store error responses returned by HMRC API , use Dapper for saving data, add unit tests

* Capitalise PayeScheme before storing it in [Cache].[AccountsResponse] table and remove empty space at the start (#86)

* Added local exceptin handling to prevent the loss of data from a batch and added repositories for storing the 'resonse' entities.

* Fixed tests

* Trim and ToUpper test fixes

* Uncomment assertions in unit tests

* Addresses PR comments

* remove redundant code

* Htb 202 handle error responses from accounts and dc ap is (#88)

* Added local exceptin handling to prevent the loss of data from a batch and added repositories for storing the 'resonse' entities.

* Fixed tests

* Trim and ToUpper test fixes

* Uncomment assertions in unit tests

* Addresses PR comments

* remove redundant code

Co-authored-by: ruslan <ruslanss@gmail.com>

* Revert "Htb 202 handle error responses from accounts and dc ap is (#88)"

This reverts commit e61505863a9b956fd3f9d6e43cf209de9e2ba082.

* Added more granular error handling.

* Suppressed compiler warning

* Removed unused exception e parameter.

* Rename test project to enable test in CI pipe-line, move repository tests to their own project which intentionally won't be picked up by CI for now)

Co-authored-by: Gary Griffiths <gary.griffiths@digital.education.gov.uk>
Co-authored-by: Peter Williams <peter.david.williams.1991@gmail.com>
Co-authored-by: PeterDavidWilliams <30286445+PeterDavidWilliams@users.noreply.github.com>
Co-authored-by: Craig Faulkner <86111246+notquitecraig@users.noreply.github.com>
Co-authored-by: Gary-Griffiths-Digital-Education <91130066+Gary-Griffiths-Digital-Education@users.noreply.github.com>
Co-authored-by: EVANS <Christian.EVANS@EDUCATION.GOV.UK>
Co-authored-by: ShakilUmar <91058007+ShakilUmar@users.noreply.github.com>